#!/bin/sh
set -e

diverted="rules/debhelper.mk class/autotools-vars.mk"

case "$1" in
    remove)
        for prog in $diverted; do
            dpkg-divert --package cdbs-embedded --remove --rename \
                --divert /usr/share/cdbs/1/$prog.cdbs /usr/share/cdbs/1/$prog
        done
    ;;

    purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
