#!/bin/sh
set -e

diverted="rules/debhelper.mk class/autotools-vars.mk class/langcore.mk"

case "$1" in
    install|upgrade)
        for prog in $diverted; do
            dpkg-divert --package cdbs-embedded --add --rename \
                --divert /usr/share/cdbs/1/$prog.cdbs /usr/share/cdbs/1/$prog
        done    
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
